# This is a basic workflow to help you get started with Actions

name: Docker Series Builds

# Controls when the workflow will run
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: docker build
        run: |
          docker build . -t cmaldonado98/trainee-tcs:registropipeline
